add_newline = false

format = """$directory$git_branch$git_status$cmd_duration
$character"""

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold white"
format = "[$path]($style)[$read_only]($read_only_style)"
read_only = " ro"

[git_branch]
symbol = ""
style = "dimmed white"
format = " [$branch]($style)"

[git_status]
style = "dimmed white"
format = "[$all_status$ahead_behind]($style)"
conflicted = " !"
ahead = " +${count}"
behind = " -${count}"
diverged = " +${ahead_count} -${behind_count}"
untracked = " ?"
stashed = " *"
modified = " ~"
staged = " +"
renamed = " >"
deleted = " x"

[character]
success_symbol = "[>](dimmed white)"
error_symbol = "[>](red)"

[cmd_duration]
min_time = 2000
format = " [$duration](dimmed white)"

[package]
disabled = true

[nodejs]
disabled = true
